// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotefunpcfveajdykydi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdGVmdW5wY2Z2ZWFqZHlreWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzM0NTksImV4cCI6MjA1OTMwOTQ1OX0.Ob39ZFFB7DgLcIYGfjS761gh5lxbXwLe-kpHOv4YZD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);